# 用户必须更改，只需更改ip、port、账号、密码，以及创建数据库，表会自动生成。
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 格式 jdbc:mysql://{mysql ip地址}:{mysql 端口}/{数据库名}
    url: jdbc:mysql://${MYSQL_HOST:81.70.118.76}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic-test}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    # mysql账号
    username: ${MYSQL_USERNAME:sonic-test}
    # mysql，密码
    password: ${MYSQL_PASSWORD:mimajiushi}
    initialization-mode: always
    schema:
      - classpath:data.sql

# 一般不需要动
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml, classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    banner: false
  configuration:
    cache-enabled: false
    localCacheScope: STATEMENT
    # sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 非开发者不要动
actable:
  model:
    pack: org.cloud.sonic.common.models.domain
  table:
    auto: update
  database:
    type: mysql